# -*- coding: utf-8 -*-
"""sol-000225613.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u32dBLGcenXK52F4eH3mlqkE1xBy-Sur
"""

import numpy as np
import pandas as pd
from scipy.spatial.distance import cdist

# Link with the database available in github for this assignment
url = 'https://raw.githubusercontent.com/ArturoSbr/appec-s2-2025/8a91c793fcd9591a7ba5d3be86ac6b7889478151/assignments/a01/data/df.csv'
df = pd.read_csv(url)

# Print head
df.head()

# (Initial Step) I was not able to run the hint code without this step...
# I'm not sure if I was doing something wrong (I probably was), but I had to add
# this initial step to create an empty column ('match') and bypass this error.
df['match'] = np.nan

# 1. Create a distance matrix (Rows: Controls, Columns: Treated)
# This calculates the squared difference between every treated unit's
# propensity score and every control unit's propensity score.
y0 = df.loc[df['treat'].eq(0), ['p_hat']].values  # Probas of control units
y1 = df.loc[df['treat'].eq(1), ['p_hat']].values  # Probas of treatment units
dist = cdist(y0, y1, metric='euclidean')
dist = dist.astype(float)

# 2. Define the Caliper (Maximum allowable distance)
# If the closest neighbor is further away than this value, we consider
# it a bad match and leave the treated unit unmatched.
THR = 0.05

# 3. Iterate through each treated unit (each column in our matrix)
for i in range(dist.shape[1]):

    # Extract the column of distances for the i-th treated unit
    # This vector contains its distance to every control unit
    a = dist[:, i]  # All rows (:), i-th column

    # Find the index of the smallest distance (the 'Nearest Neighbor')
    idx = np.argmin(a)
    val = a[idx]  # Fetch distance between the two

    # 4. Apply the Caliper constraint
    if val <= THR and val != np.inf:

        # Identify the original DataFrame index for the treated unit
        idx_1 = df[df['treat'].eq(1)].iloc[i].name.item()

        # Identify the original DataFrame index for the chosen control unit
        idx_0 = df[df['treat'].eq(0)].iloc[idx].name.item()

        # Store the match: link the treated ID to the control ID
        df.loc[idx_1, 'match'] = idx_0

        # 5. (ADJUSTMENT & PROPOSED SOLUTION) This is the proposed main adjustment
        # in the code to make it without replacement... The idea is to subscribe the
        # copntrols in the pairing matrx with infinite values, so que the next
        # iterations run, the code will ignore those values and look for the next
        # available distance.
        dist[idx, :] = np.inf

# 6. Print the results
print(df[df['treat'] == 1][['treat', 'p_hat', 'match']].head(10))

# (FINAL VALIDATION) I was not able to check if my code was really doing
# the matching without replacement, so I asked Gemini to help me visualize it by
# counting how many times each control observation was being used.

controles_asignados = df.loc[df['treat'] == 1, 'match'].dropna()
cantidad_repetidos = controles_asignados.duplicated().sum()

print(f"Total formed pairs: {len(controles_asignados)}")
print(f"Controls used more than once: {cantidad_repetidos}")