name: Autograder CI

on:
  push:
    branches:
      - 'final/*'

jobs:
  autograding-final:
    name: Run Final Exam Autograder
    if: startsWith(github.ref, 'refs/heads/final/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r grader-requirements.txt

      - name: Final Exam Autograder
        run: |
          echo "Triggered by a push to branch: ${{ github.ref_name }}"
          python .github/grader/final/final_grader.py
